[package]
name = "my_library"
version = "0.1.0"
authors = ["BuRny <gamingburny@gmail.com>"]
edition = "2018"

[lib]
name = "my_library"
crate-type = ["cdylib"]

[dependencies]
cute = "0.3.0"
#numpy = "0.7.0"
#ndarray = "0.13"
pathfinding = "2.0.3"

[dependencies.pyo3]
version = "0.8.4"
features = ["extension-module"]
