name: RustBuild
on: [push]

jobs:
  build:
    name: Build release

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [nightly]
        python-version: [3.7, 3.8, 3.9]

    steps:
    # https://github.com/actions-rs/toolchain
    - uses: actions/checkout@v1

    # Cache
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        # rustup override set nightly-YYYY-MM-DD
        toolchain: nightly-2021-03-16
        override: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python requirements
      run: |
        pip install poetry
        poetry install

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run clippy
      run: |
        rustup component add clippy
        cargo clippy

    - name: Test
      run: cargo test --verbose --release --no-default-features

    - name: Bench
      run: cargo bench --no-default-features

    - name: Build
      run: cargo build --verbose --release

    - name: Run python script with library (linux)
      run: |
        poetry run python compile.py
        poetry run python src/main.py
      if: matrix.os == 'ubuntu-latest'

    - name: Run python script with library (windows)
      run: |
        dir target/release
        poetry run python compile.py
        poetry run python src/main.py
      if: matrix.os == 'windows-latest'

    - name: Create artifact directory
      run: mkdir artifacts

    # TODO only one .so file needs to be built and it can be run from any python version on the linux distribution, and this probably also works on mac
    - name: Create archive for Linux
      run: |
        sudo apt-get install tree
        tree target/release
        mv ./target/release/libmy_library.so ./artifacts/my_library.so
#        7z a -ttar -so -an ./target/release/libmy_library.so ${{ env.RELEASE_ADDS }} | 7z a -si ./artifacts/${{ env.RELEASE_LIB }}-linux-x86_64.tar.gz
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.7'

    - name: Create archive for Windows
      run: |
        dir target/release
        python move.py ${{ matrix.python-version }}
#        move ./target/release/my_library.dll ./artifacts/my_lib.pyd
#        move ./target/release/my_library.dll ./artifacts/my_lib.cp${{}}.pyd
#        7z a -tzip ./artifacts/${{ env.RELEASE_LIB }}-windows-x86_64.zip ./target/release/my_library.dll
      if: matrix.os == 'windows-latest'

    # See - https://github.com/actions/upload-artifact/issues/39
    - uses: actions/upload-artifact@v1
      name: Upload archive
      with:
        name: ${{ matrix.os }}_python${{ matrix.python-version }}
        path: artifacts/
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.7' || matrix.os == 'windows-latest'
